from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import darkblue


def create_report(patient, result, score, hospital, ai_response):

    filename = "Emergency_Report.pdf"

    doc = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    title_style = styles["Heading1"]
    title_style.alignment = TA_CENTER
    title_style.textColor = darkblue

    story = []

    # -------------------------
    # Title
    # -------------------------

    story.append(Paragraph("🏥 Smart Hospital Resource Network", title_style))
    story.append(Spacer(1, 20))

    story.append(Paragraph("<b>Emergency AI Report</b>", styles["Heading2"]))
    story.append(Spacer(1, 15))

    # -------------------------
    # Patient Details
    # -------------------------

    story.append(Paragraph("<b>Patient Information</b>", styles["Heading3"]))

    story.append(Paragraph(f"Age: {patient['age']}", styles["Normal"]))
    story.append(Paragraph(f"Gender: {patient['gender']}", styles["Normal"]))
    story.append(Paragraph(f"Symptom: {patient['symptom']}", styles["Normal"]))
    story.append(Paragraph(f"Oxygen: {patient['oxygen']}%", styles["Normal"]))
    story.append(Paragraph(f"Heart Rate: {patient['heart_rate']} BPM", styles["Normal"]))
    story.append(Paragraph(f"Blood Pressure: {patient['bp']} mmHg", styles["Normal"]))
    story.append(Paragraph(f"Temperature: {patient['temperature']} °C", styles["Normal"]))
    story.append(Paragraph(f"Respiratory Rate: {patient['respiratory_rate']}", styles["Normal"]))

    story.append(Spacer(1, 20))

    # -------------------------
    # AI Assessment
    # -------------------------

    story.append(Paragraph("<b>AI Assessment</b>", styles["Heading3"]))

    story.append(Paragraph(f"Risk Level: {result}", styles["Normal"]))
    story.append(Paragraph(f"Risk Score: {score}/100", styles["Normal"]))

    story.append(Spacer(1, 20))

    # -------------------------
    # Hospital Recommendation
    # -------------------------

    story.append(Paragraph("<b>Recommended Hospital</b>", styles["Heading3"]))

    story.append(Paragraph(f"Hospital: {hospital['Hospital']}", styles["Normal"]))
    story.append(Paragraph(f"City: {hospital['City']}", styles["Normal"]))
    story.append(Paragraph(f"Available ICU Beds: {hospital['Beds']}", styles["Normal"]))
    story.append(Paragraph(f"Ventilators: {hospital['Ventilators']}", styles["Normal"]))
    story.append(Paragraph(f"Hospital Score: {hospital['Score']}", styles["Normal"]))

    story.append(Spacer(1, 20))

    # -------------------------
    # AI Medical Assistant
    # -------------------------

    story.append(Paragraph("<b>AI Medical Advice</b>", styles["Heading3"]))

    ai_response = ai_response.replace("\n", "<br/>")

    story.append(Paragraph(ai_response, styles["BodyText"]))

    story.append(Spacer(1, 20))

    # -------------------------
    # Footer
    # -------------------------

    story.append(
        Paragraph(
            "<b>Disclaimer:</b> This report is generated by an AI prototype for hackathon demonstration purposes only and should not replace professional medical advice.",
            styles["Italic"],
        )
    )

    doc.build(story)

    return filename